server:
    port: 80
spring:
    application:
        name: cloud-order-80

# Eureka配置
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka.7001.com:7001/eureka/
            # defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/
    instance:
        # Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认为30秒)
        lease-renewal-interval-in-seconds: 3
        # Eureka服务端在接收到客户端最后一次心跳的时间上限(默认为90秒)，超时将剔除服务
        lease-expiration-duration-in-seconds: 10
