server:
    port: 7001  # 服务端口号
# Eureka配置
eureka:
    instance:
        hostname: eureka.7001.com
        # 单机版
        # hostname: localhost   # Eureka服务端实例的名称
    client:
        register-with-eureka: false   # 表示不向注册中心注册自己
        fetch-registry: false          # false表示自己就是服务注册
        service-url:
            # 单机版是指向自己
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 设置与Eureka Server交互的地址查询服务和交互服务都需要依赖这个地址
            # 多级版是指向其他EurekaServer地址
            # defaultZone: http://eureka.7002.com/eureka/
    server:
        enable-self-preservation: false     # 服务端自我保护机制
        eviction-interval-timer-in-ms: 2000 # 清理间隔